
package org.eclipse.webservices.soap.weatherservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.5
 * Mon May 23 17:30:32 CEST 2016
 * Generated source version: 3.1.5
 */

@XmlRootElement(name = "getTimeofWeatherObservationResponse", namespace = "http://weatherservice.soap.webservices.eclipse.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTimeofWeatherObservationResponse", namespace = "http://weatherservice.soap.webservices.eclipse.org/")

public class GetTimeofWeatherObservationResponse {

    @XmlElement(name = "TimeOfWeatherObservation")
    private java.lang.String TimeOfWeatherObservation;

    public java.lang.String getTimeOfWeatherObservation() {
        return this.TimeOfWeatherObservation;
    }

    public void setTimeOfWeatherObservation(java.lang.String newTimeOfWeatherObservation)  {
        this.TimeOfWeatherObservation = newTimeOfWeatherObservation;
    }

}

